
services:
  mailing-service:
    image: ghcr.io/woutdepeuter/integration-project-groep2-mailing:latest
    labels:
      co.elastic.metrics/module: prometheus
      co.elastic.metrics/hosts: '$${data.host}:8080'
      co.elastic.metrics/metricsets: collector
      co.elastic.metrics/metrics_path: /actuator/prometheus
      co.elastic.metrics/period: 10s
    networks:
      - attendify_net
      - mailing
    environment:
      - 'LOG_LEVEL=debug'
      - 'DB_HOST=mysql'
      - 'DB_AUTH_PASS=${DB_AUTH_PASS}'
      - 'RABBITMQ_HOST=${RABBITMQ_HOST}'
      - 'RABBITMQ_PASS=${RABBITMQ_PASS}'
      - 'SENDGRID_API_KEY=${SENDGRID_API_KEY}'
      - 'SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql:latest'
    networks:
      - mailing
    volumes:
      - mysql-mailing:/var/lib/mysql:rw
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_AUTH_PASS}'
      - 'MYSQL_ROOT_PASSWORD=${DB_AUTH_ROOT_PASS}'
      - 'MYSQL_USER=${DB_AUTH_USER}'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p=$DB_AUTH_ROOT_PASS" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  mysql-mailing: {}

networks:
  attendify_net:
    external: true
  mailing:
