
services:
  mailing-service:
    image: ghcr.io/woutdepeuter/integration-project-groep2-mailing:latest
    labels:
      co.elastic.metrics/module: prometheus
      co.elastic.metrics/metricsets: collector
      co.elastic.metrics/metrics_path: /actuator/prometheus
      co.elastic.metrics/period: 10s
    networks:
      - attendify_net
      - mailing
    environment:
      - 'LOG_LEVEL=debug'
      - 'DB_HOST=mysql'
      - 'DB_AUTH_PASS=changeme'
      - 'RABBITMQ_HOST=changeme'
      - 'RABBITMQ_PASS=changeme'
      - 'SENDGRID_API_KEY=changeme'
      - 'SENDGRID_FROM_EMAIL=changeme'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql:latest'
    networks:
      - mailing
    volumes:
      - mysql-mailing:/var/lib/mysql:rw
    environment:
      - 'MYSQL_DATABASE=mailing_service'
      - 'MYSQL_PASSWORD=changeme'
      - 'MYSQL_ROOT_PASSWORD=changeme'
      - 'MYSQL_USER=mailing_dev'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p=changeme" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  mysql-mailing: {}

networks:
  attendify_net:
    external: true
  mailing:
