name: Gradle Build and Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  upload-container:
    name: Build & Upload container to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from build.gradle.kts
        id: get_version
        run: echo "VERSION=$(grep 'version =' build.gradle.kts | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/woutdepeuter/integration-project-groep2-mailing:latest
          build-args: |
            VERSION=${{ env.VERSION }}